### ISSUE TITLE
Create a share icon that allows user share task in the chat.

### ISSUE THREAD

**Issue by Kemmie001** [zurichat/zc_plugin_todo#89]

**Comment by Emie-cloud** [comment]
USER STORY ID - Share
AS A - all users
I WANT TO- share a file or task with a group of persons through Email or link invite
SO THAT I CAN - to make it easy for anyone assigned a task to be notified of when a task drops and also be able to invite any external guests to view the project, comment or edit as the case may be

https://www.figma.com/file/qmhEDtQD5rvb3Txt6nyqgp/Team-kant-task?node-id=0%3A1

**Comment by Emie-cloud** [comment]
USER STORY ID - Share
AS A - all users
I WANT TO- share a file or task with a group of persons through Email or link invite
SO THAT I CAN - to make it easy for anyone assigned a task to be notified of when a task drops and also be able to invite any external guests to view the project, comment or edit as the case may be

https://www.figma.com/file/qmhEDtQD5rvb3Txt6nyqgp/Team-kant-task?node-id=0%3A1
